### ISSUE TITLE
5_undefinded

### ISSUE THREAD

**Issue by iamrandle** [pahjay/altum#3]
Console reads:

"deleting 5_undefined_bronze
deleting 5_undefined_gold
deleting 5_undefined_silver"

at some point after a user joins the lobby.

**Comment by ryanpag3** [comment]
I can't seem to reproduce this on my end. Maybe it's specific to your branch?

**Comment by ryanpag3** [comment]
Issue was due to @iamrandle having a out-of-date game-list schema. Local bug only, closing issue.
